# This is a basic workflow to help you get started with Actions
# ==================================
# GitHub Action Part-1
# ==================================
name: My-GitHubAction-Basics

env: 
  APPLICATION_NAME    : "My_F"
  DEPLOY_PACKAGE_NAME : "my_foo-${{ github.sha }}"

on:
  push:
    branches: [master]
jobs:
  my_testing:
    runs-on: ubuntu-latest
    steps:
    - name: Print Message Testing
      run: echo Hello, world from Testing

    - name: Git clone my repo
      uses: actions/checkout@v1

    - name: Выполнение нескольких команд
      run: |
        echo "================================="
        echo Несколько команд друг за другом
        cat /etc/*release
        echo "================================="
        ls -la
        echo "================================="

  my_deploy:
    needs: [my_testing]
    runs-on: ubuntu-latest
    steps:
    - name: Print Message Deploy
      run: echo Hello, world from Deploy

    - name: Проверка наличия пакетов
      run: |
        aws version
        zip

